cities = [
    "Adana",
    "Adıyaman",
    "Afyonkarahisar",
    "Ağrı",
    "Amasya",
    "Ankara",
    "Antalya",
    "Artvin",
    "Aydın",
    "Balıkesir",
    "Bilecik",
    "Bingöl",
    "Bitlis",
    "Bolu",
    "Burdur",
    "Bursa",
    "Çanakkale",
    "Çankırı",
    "Çorum",
    "Denizli",
    "Diyarbakır",
    "Edirne",
    "Elazığ",
    "Erzincan",
    "Erzurum",
    "Eskişehir",
    "Gaziantep",
    "Giresun",
    "Gümüşhane",
    "Hakkari",
    "Hatay",
    "Isparta",
    "Mersin",
    "İstanbul",
    "İzmir",
    "Kars",
    "Kastamonu",
    "Kayseri",
    "Kırklareli",
    "Kırşehir",
    "Kocaeli",
    "Konya",
    "Kütahya",
    "Malatya",
    "Manisa",
    "Kahramanmaraş",
    "Mardin",
    "Muğla",
    "Muş",
    "Nevşehir",
    "Niğde",
    "Ordu",
    "Rize",
    "Sakarya",
    "Samsun",
    "Siirt",
    "Sinop",
    "Sivas",
    "Tekirdağ",
    "Tokat",
    "Trabzon",
    "Tunceli",
    "Şanlıurfa",
    "Uşak",
    "Van",
    "Yozgat",
    "Zonguldak",
    "Aksaray",
    "Bayburt",
    "Karaman",
    "Kırıkkale",
    "Batman",
    "Şırnak",
    "Bartın",
    "Ardahan",
    "Iğdır",
    "Yalova",
    "Karabük",
    "Kilis",
    "Osmaniye",
    "Düzce",
]

regions = [
    "Marmara",
    "İç Anadolu",
    "Ege",
    "Akdeniz",
    "Karadeniz",
    "Doğu Anadolu",
    "Güneydoğu Anadolu",
]

cities_by_region = {
    "Marmara": [
        "Edirne",
        "Kırklareli",
        "Tekirdağ",
        "İstanbul",
        "Kocaeli",
        "Yalova",
        "Sakarya",
        "Bilecik",
        "Bursa",
        "Balıkesir",
        "Çanakkale",
    ],
    "İç Anadolu": [
        "Aksaray",
        "Ankara",
        "Çankırı",
        "Eskişehir",
        "Karaman",
        "Kırıkkale",
        "Kırşehir",
        "Konya",
        "Nevşehir",
        "Niğde",
        "Sivas",
        "Yozgat",
        "Kayseri",
    ],
    "Ege": [
        "İzmir",
        "Manisa",
        "Aydın",
        "Denizli",
        "Kütahya",
        "Afyonkarahisar",
        "Uşak",
        "Muğla",
    ],
    "Akdeniz": [
        "Adana",
        "Osmaniye",
        "Antalya",
        "Burdur",
        "Hatay",
        "Isparta",
        "Mersin",
        "Kahramanmaraş",
    ],
    "Karadeniz": [
        "Rize",
        "Trabzon",
        "Artvin",
        "Sinop",
        "Tokat",
        "Çorum",
        "Amasya",
        "Samsun",
        "Zonguldak",
        "Bolu",
        "Düzce",
        "Karabük",
        "Bartın",
        "Kastamonu",
        "Bayburt",
        "Giresun",
        "Gümüşhane",
        "Ordu",
    ],
    "Doğu Anadolu": [
        "Ağrı",
        "Ardahan",
        "Bingöl",
        "Bitlis",
        "Elazığ",
        "Erzincan",
        "Erzurum",
        "Hakkari",
        "Iğdır",
        "Kars",
        "Malatya",
        "Muş",
        "Tunceli",
        "Van",
        "Şırnak",
    ],
    "Güneydoğu Anadolu": [
        "Adıyaman",
        "Batman",
        "Diyarbakır",
        "Gaziantep",
        "Kilis",
        "Mardin",
        "Siirt",
        "Şanlıurfa",
    ],
}

cities_w_codes = {
    1: "Adana",
    2: "Adıyaman",
    3: "Afyonkarahisar",
    4: "Ağrı",
    5: "Amasya",
    6: "Ankara",
    7: "Antalya",
    8: "Artvin",
    9: "Aydın",
    10: "Balıkesir",
    11: "Bilecik",
    12: "Bingöl",
    13: "Bitlis",
    14: "Bolu",
    15: "Burdur",
    16: "Bursa",
    17: "Çanakkale",
    18: "Çankırı",
    19: "Çorum",
    20: "Denizli",
    21: "Diyarbakır",
    22: "Edirne",
    23: "Elazığ",
    24: "Erzincan",
    25: "Erzurum",
    26: "Eskişehir",
    27: "Gaziantep",
    28: "Giresun",
    29: "Gümüşhane",
    30: "Hakkari",
    31: "Hatay",
    32: "Isparta",
    33: "Mersin",
    34: "İstanbul",
    35: "İzmir",
    36: "Kars",
    37: "Kastamonu",
    38: "Kayseri",
    39: "Kırklareli",
    40: "Kırşehir",
    41: "Kocaeli",
    42: "Konya",
    43: "Kütahya",
    44: "Malatya",
    45: "Manisa",
    46: "Kahramanmaraş",
    47: "Mardin",
    48: "Muğla",
    49: "Muş",
    50: "Nevşehir",
    51: "Niğde",
    52: "Ordu",
    53: "Rize",
    54: "Sakarya",
    55: "Samsun",
    56: "Siirt",
    57: "Sinop",
    58: "Sivas",
    59: "Tekirdağ",
    60: "Tokat",
    61: "Trabzon",
    62: "Tunceli",
    63: "Şanlıurfa",
    64: "Uşak",
    65: "Van",
    66: "Yozgat",
    67: "Zonguldak",
    68: "Aksaray",
    69: "Bayburt",
    70: "Karaman",
    71: "Kırıkkale",
    72: "Batman",
    73: "Şırnak",
    74: "Bartın",
    75: "Ardahan",
    76: "Iğdır",
    77: "Yalova",
    78: "Karabük",
    79: "Kilis",
    80: "Osmaniye",
    81: "Düzce",
}

cities_inverse = {v: k for k, v in cities_w_codes.items()}

regions_w_codes = {
    "Marmara": [
        cities_inverse[name]
        for name in [
            "Edirne",
            "Kırklareli",
            "Tekirdağ",
            "İstanbul",
            "Kocaeli",
            "Yalova",
            "Sakarya",
            "Bilecik",
            "Bursa",
            "Balıkesir",
            "Çanakkale",
        ]
    ],
    "İç Anadolu": [
        cities_inverse[name]
        for name in [
            "Aksaray",
            "Ankara",
            "Çankırı",
            "Eskişehir",
            "Karaman",
            "Kırıkkale",
            "Kırşehir",
            "Konya",
            "Nevşehir",
            "Niğde",
            "Sivas",
            "Yozgat",
            "Kayseri",
        ]
    ],
    "Ege": [
        cities_inverse[name]
        for name in [
            "İzmir",
            "Manisa",
            "Aydın",
            "Denizli",
            "Kütahya",
            "Afyonkarahisar",
            "Uşak",
            "Muğla",
        ]
    ],
    "Akdeniz": [
        cities_inverse[name]
        for name in [
            "Adana",
            "Osmaniye",
            "Antalya",
            "Burdur",
            "Hatay",
            "Isparta",
            "Mersin",
            "Kahramanmaraş",
        ]
    ],
    "Karadeniz": [
        cities_inverse[name]
        for name in [
            "Rize",
            "Trabzon",
            "Artvin",
            "Sinop",
            "Tokat",
            "Çorum",
            "Amasya",
            "Samsun",
            "Zonguldak",
            "Bolu",
            "Düzce",
            "Karabük",
            "Bartın",
            "Kastamonu",
            "Bayburt",
            "Giresun",
            "Gümüşhane",
            "Ordu",
        ]
    ],
    "Doğu Anadolu": [
        cities_inverse[name]
        for name in [
            "Ağrı",
            "Ardahan",
            "Bingöl",
            "Bitlis",
            "Elazığ",
            "Erzincan",
            "Erzurum",
            "Hakkari",
            "Iğdır",
            "Kars",
            "Malatya",
            "Muş",
            "Tunceli",
            "Van",
            "Şırnak",
        ]
    ],
    "Güneydoğu Anadolu": [
        cities_inverse[name]
        for name in [
            "Adıyaman",
            "Batman",
            "Diyarbakır",
            "Gaziantep",
            "Kilis",
            "Mardin",
            "Siirt",
            "Şanlıurfa",
        ]
    ],
}

first_names_male = [
    "Ahmet",
    "Mehmet",
    "Ali",
    "Emre",
    "Can",
    "Murat",
    "Yusuf",
    "Hakan",
    "Ozan",
    "Kemal",
]

first_names_female = [
    "Ayşe",
    "Fatma",
    "Elif",
    "Zeynep",
    "Yasemin",
    "Derya",
    "Seda",
    "Ebru",
    "Aslı",
    "Hande",
]

surnames = [
    "Yılmaz",
    "Demir",
    "Öztürk",
    "Kaya",
    "Şahin",
    "Çelik",
    "Yıldız",
    "Akar",
    "Tezcan",
    "Kurt",
]
